quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('quotes_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/quotes_app/urls.py
from django.urls import path

from . import views
from .apps import QuotesAppConfig


app_name = QuotesAppConfig.name


urlpatterns = [
    path('', views.main, {"page_id": 1}, name='main'),
    path('add-author/', views.add_author, name='add-author'),
    path('add-quote/', views.add_quote, name='add-quote'),
    path('add-tag/', views.add_tag, name='add-tag'),
    path('author/<str:author_full_name_url>/', views.author, name='author'),
    path('tag/<str:tag_title>/', views.tag, {"page_id": 1}, name='tag'),
    path('top-tags/', views.top_tags, name='top-tags'),
    path('page/<int:page_id>/', views.main, name='main-page-id'),
    path('tag/<str:tag_title>/page/<int:page_id>/', views.tag, name='tag-page-id'),
]

quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views


app_name = "users"


urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quotes_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_hybrid_attributes import hybrid_property, HybridQuerySet


# Create your models here.
class Author(models.Model):
    full_name = models.CharField(max_length=150, null=False, unique=True)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=150, null=False)
    description = models.CharField(max_length=10000, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    objects = HybridQuerySet.as_manager()

    @hybrid_property
    def full_name_url(self):
        return self.full_name.replace(" ", "-")

    @full_name_url.expression
    def full_name_url(cls):
        return models.functions.Replace(
            "full_name", models.Value(" "), models.Value("-")
        )

    def __str__(self):
        return f"{self.full_name}"


class Tag(models.Model):
    title = models.CharField(max_length=50, null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"#{self.title}"


class Quote(models.Model):
    quote = models.CharField(max_length=10000, null=False, unique=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.quote}"

quotes/quotes_app/forms.py
from django.forms import ModelForm, CharField, DateField, TextInput, DateInput, Textarea
from django import forms

from .models import Author, Tag, Quote


class DateInput(DateInput):
    input_type = "date"


class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(
        min_length=2,
        max_length=150,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "Input full_name",
            }
        ),
    )
    born_date = DateField(
        required=True,
        widget=DateInput(
            attrs={
                "class": "form-control",
                # "placeholder": "Input born date",
            }
        ),
    )
    born_location = forms.CharField(
        min_length=2,
        max_length=150,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "Input born location",
            }
        ),
    )
    description = forms.CharField(
        min_length=10,
        max_length=10000,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                # "placeholder": "Input description",
            }
        ),
    )

    class Meta:
        model = Author
        fields = ["full_name", "born_date", "born_location", "description"]


class QuoteForm(forms.ModelForm):
    quote = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": "5"})
    )
    author = forms.ModelChoiceField(
        queryset=Author.objects.all().order_by("full_name"),
        empty_label=" -- select an option -- ",
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("title"),
        widget=forms.SelectMultiple(
            attrs={
                "size": "12",
            },
        ),
    )

    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]


class TagForm(ModelForm):
    title = CharField(min_length=1, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["title"]

quotes/quotes_app/views.py
import re

from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import redirect, render, get_object_or_404

from .models import Author, Tag, Quote
from .forms import AuthorForm, TagForm, QuoteForm


NUMBER_OF_QUOTES_PER_PAGE = 10
NUMBER_OF_TOP_TAGS = 10


def get_quote_tags_list_per_page_and_page_ids(quotes, page_id):
    quote_tags_list = []
    len_of_quotes = len(quotes)
    previous_page_id = page_id - 1
    OFFSET = NUMBER_OF_QUOTES_PER_PAGE * previous_page_id
    LIMIT = NUMBER_OF_QUOTES_PER_PAGE * page_id
    if LIMIT >= len_of_quotes:
        LIMIT = len_of_quotes
        next_page_id = 0
    else:
        next_page_id = page_id + 1
    quotes = quotes[OFFSET:LIMIT]
    for quote in quotes:
        tags = quote.tags.all()
        quote_tags_list.append((quote, tags))
    return quote_tags_list, previous_page_id, next_page_id


# Create your views here.
def main(request, page_id):
    quotes = Quote.objects.all()
    (
        quote_tags_list,
        previous_page_id,
        next_page_id,
    ) = get_quote_tags_list_per_page_and_page_ids(quotes, page_id)
    context = {
        "quote_tags_list": quote_tags_list,
        "previous_page_id": previous_page_id,
        "next_page_id": next_page_id,
    }
    return render(request, "quotes_app/index.html", context)


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.born_location = re.sub(
                "^in ", "", author.born_location, flags=re.IGNORECASE
            )
            author.added_by = request.user
            author.save()
            return redirect(to="quotes_app:main")
        else:
            return render(request, "quotes_app/add_author.html", {"form": form})
    return render(request, "quotes_app/add_author.html", {"form": AuthorForm()})


@login_required
def add_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.added_by = request.user
            tag.title = tag.title.replace("#", "")
            tag.save()
            return redirect(to="quotes_app:main")
        else:
            return render(request, "quotes_app/add_tag.html", {"form": form})
    return render(request, "quotes_app/add_tag.html", {"form": TagForm()})


@login_required
def add_quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.added_by = request.user
            new_quote.save()
            choice_tags = Tag.objects.filter(id__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            return redirect(to="quotes_app:main")
        else:
            return render(
                request,
                "quotes_app/add_quote.html",
                {"authors": authors, "tags": tags, "form": form},
            )
    return render(
        request,
        "quotes_app/add_quote.html",
        {"authors": authors, "tags": tags, "form": QuoteForm()},
    )


def author(request, author_full_name_url):
    author = Author.objects.filter(Author.full_name_url == author_full_name_url).first()
    return render(request, "quotes_app/author.html", {"author": author})


def tag(request, tag_title, page_id):
    tag = get_object_or_404(Tag, title=tag_title)
    quotes = Quote.objects.filter(tags__in=[tag])
    (
        quote_tags_list,
        previous_page_id,
        next_page_id,
    ) = get_quote_tags_list_per_page_and_page_ids(quotes, page_id)
    context = {
        "quote_tags_list": quote_tags_list,
        "previous_page_id": previous_page_id,
        "next_page_id": next_page_id,
        "tag_title": tag_title,
    }
    return render(request, "quotes_app/tag.html", context)


def top_tags(request):
    tags = Tag.objects.annotate(num_quote=Count("quote")).order_by("-num_quote")[
        :NUMBER_OF_TOP_TAGS
    ]
    return render(request, "quotes_app/top_tags.html", {"tags": tags})

quotes/quotes_app/templates/quotes_app/add_author.html
{% extends "quotes_app/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_app:add-author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author's full name:
            {{ form.full_name }}
        </label>
        <span>{{ form.errors.full_name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/quotes_app/add_quote.html
{% extends "quotes_app/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_app:add-quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/quotes_app/add_tag.html
{% extends "quotes_app/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_app:add-tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag's title:
            {{ form.title }}
        </label>
        <span>{{ form.errors.title }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/quotes_app/author.html
{% extends "quotes_app/base.html" %}

{% block content %}

{% if author %}
    <h1>{{ author.full_name }}</h1>
    <p><b>Born:</b> {{ author.born_date }}&nbsp;in&nbsp;{{ author.born_location }}</p>
    <p><b>Description:</b> <p>{{ author.description }}</p></p>
{% else %}
Author not found!<p></p>
{% endif %}

{% endblock %}

quotes/quotes_app/templates/quotes_app/author_info.html
{% extends "quotes_app/base.html" %}

{% block content %}

<h1>{{author.fullname}}</h1>
<p><b>Born:</b> {{author.born_date}}&nbsp;in&nbsp;{{author.born_location}}</p>
<p><b>Description:</b> <p>{{author.description}}</p></p>

{% endblock %}

quotes/quotes_app/templates/quotes_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_app/style.css' %}">
</head>

<body>
    <div class="container-fluid">
        <h1><a href="/">Quotes</a></h1>
        <a href="{% url 'quotes_app:top-tags' %}">Top Ten tags</a>
    </div>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quotes_app:add-author' %}" role="button">Add author</a></li>
                <li><a href="{% url 'quotes_app:add-quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quotes_app:add-tag' %}" role="button">Add tag</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

quotes/quotes_app/templates/quotes_app/index.html
{% extends "quotes_app/base.html" %}

{% block content %}

{% if quote_tags_list %}
    {% for quote, tags in quote_tags_list %}
    <ul>
        <li>
            <i>{{ quote.quote }}</i>
            <p><a href="{% url 'quotes_app:author' quote.author.full_name_url %}">{{ quote.author }}</a></p>
            {% if tags %}
                <p>Tags: 
                    <small> 
                        {% for tag in tags %}
                            <a href="{% url 'quotes_app:tag' tag.title %}">#{{ tag.title }}</a>
                        {% endfor %}
                    </small>
                </p>
            {% endif %}
            <br>
        </li>
    </ul>
    {% endfor %}
{% else %}
No quotes found!<p></p>
{% endif %}
{% if previous_page_id or next_page_id %}
<ul>
    {% if previous_page_id %}
        <span style="float:left;"><a href="{% url 'quotes_app:main-page-id' previous_page_id %}" role="button"><span aria-hidden="true">←</span> Previous</a></span>
    {% endif %}
    {% if next_page_id %}
        <span style="float:right;"><a href="{% url 'quotes_app:main-page-id' next_page_id %}" role="button">Next <span aria-hidden="true">→</span></a></span>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

quotes/quotes_app/templates/quotes_app/quote.html
{% extends "quotes_app/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_app:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="authors">
                <option disabled selected value> -- select an option -- </option>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.title}}">{{tag.title}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotes_app/templates/quotes_app/tag.html
{% extends "quotes_app/base.html" %}

{% block content %}

{% if quote_tags_list %}
    {% for quote, tags in quote_tags_list %}
    <ul>
        <li>
            <i>{{ quote.quote }}</i>
            <p><a href="{% url 'quotes_app:author' quote.author.full_name_url %}">{{ quote.author }}</a></p>
            {% if tags %}
                <p>Tags: 
                    <small> 
                        {% for tag in tags %}
                            <a href="{% url 'quotes_app:tag' tag.title %}">#{{ tag.title }}</a>
                        {% endfor %}
                    </small>
                </p>
            {% endif %}
            <br>
        </li>
    </ul>
    {% endfor %}
{% else %}
No quotes found!<p></p>
{% endif %}
{% if previous_page_id or next_page_id %}
<ul>
    {% if previous_page_id %}
        <span style="float:left;"><a href="{% url 'quotes_app:tag-page-id' tag_title previous_page_id %}" role="button"><span aria-hidden="true">←</span> Previous</a></span>
    {% endif %}
    {% if next_page_id %}
        <span style="float:right;"><a href="{% url 'quotes_app:tag-page-id' tag_title next_page_id %}" role="button">Next <span aria-hidden="true">→</span></a></span>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

quotes/quotes_app/templates/quotes_app/top_tags.html
{% extends "quotes_app/base.html" %}

{% block content %}

{% if tags %}
    {% for tag in tags %}
    <ul>
        <li>
            <p><a href="{% url 'quotes_app:tag' tag.title %}">#{{ tag.title }}</a></p>
        </li>
    </ul>
    {% endfor %}
{% else %}
No tags found!<p></p>
{% endif %}

{% endblock %}